//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace QTMS.SubContracttor_Report {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsBulkTDB_Report_SubContract")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsBulkTDB_Report_SubContract : global::System.Data.DataSet {
        
        private VIEW_BulkTDB_Report_SubContractDataTable tableVIEW_BulkTDB_Report_SubContract;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public dsBulkTDB_Report_SubContract() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected dsBulkTDB_Report_SubContract(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["VIEW_BulkTDB_Report_SubContract"] != null)) {
                    base.Tables.Add(new VIEW_BulkTDB_Report_SubContractDataTable(ds.Tables["VIEW_BulkTDB_Report_SubContract"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public VIEW_BulkTDB_Report_SubContractDataTable VIEW_BulkTDB_Report_SubContract {
            get {
                return this.tableVIEW_BulkTDB_Report_SubContract;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            dsBulkTDB_Report_SubContract cln = ((dsBulkTDB_Report_SubContract)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["VIEW_BulkTDB_Report_SubContract"] != null)) {
                    base.Tables.Add(new VIEW_BulkTDB_Report_SubContractDataTable(ds.Tables["VIEW_BulkTDB_Report_SubContract"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableVIEW_BulkTDB_Report_SubContract = ((VIEW_BulkTDB_Report_SubContractDataTable)(base.Tables["VIEW_BulkTDB_Report_SubContract"]));
            if ((initTable == true)) {
                if ((this.tableVIEW_BulkTDB_Report_SubContract != null)) {
                    this.tableVIEW_BulkTDB_Report_SubContract.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "dsBulkTDB_Report_SubContract";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsBulkTDB_Report_SubContract.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableVIEW_BulkTDB_Report_SubContract = new VIEW_BulkTDB_Report_SubContractDataTable();
            base.Tables.Add(this.tableVIEW_BulkTDB_Report_SubContract);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeVIEW_BulkTDB_Report_SubContract() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsBulkTDB_Report_SubContract ds = new dsBulkTDB_Report_SubContract();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void VIEW_BulkTDB_Report_SubContractRowChangeEventHandler(object sender, VIEW_BulkTDB_Report_SubContractRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class VIEW_BulkTDB_Report_SubContractDataTable : global::System.Data.DataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columnInspDate;
            
            private global::System.Data.DataColumn columnFamilyDesc;
            
            private global::System.Data.DataColumn columnBPCNONBPC;
            
            private global::System.Data.DataColumn columnStatus;
            
            private global::System.Data.DataColumn columnSubContract;
            
            private global::System.Data.DataColumn columnFlagRL;
            
            private global::System.Data.DataColumn columnFormulaType;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public VIEW_BulkTDB_Report_SubContractDataTable() {
                this.TableName = "VIEW_BulkTDB_Report_SubContract";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal VIEW_BulkTDB_Report_SubContractDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected VIEW_BulkTDB_Report_SubContractDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn InspDateColumn {
                get {
                    return this.columnInspDate;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn FamilyDescColumn {
                get {
                    return this.columnFamilyDesc;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn BPCNONBPCColumn {
                get {
                    return this.columnBPCNONBPC;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn StatusColumn {
                get {
                    return this.columnStatus;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SubContractColumn {
                get {
                    return this.columnSubContract;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn FlagRLColumn {
                get {
                    return this.columnFlagRL;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn FormulaTypeColumn {
                get {
                    return this.columnFormulaType;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public VIEW_BulkTDB_Report_SubContractRow this[int index] {
                get {
                    return ((VIEW_BulkTDB_Report_SubContractRow)(this.Rows[index]));
                }
            }
            
            public event VIEW_BulkTDB_Report_SubContractRowChangeEventHandler VIEW_BulkTDB_Report_SubContractRowChanging;
            
            public event VIEW_BulkTDB_Report_SubContractRowChangeEventHandler VIEW_BulkTDB_Report_SubContractRowChanged;
            
            public event VIEW_BulkTDB_Report_SubContractRowChangeEventHandler VIEW_BulkTDB_Report_SubContractRowDeleting;
            
            public event VIEW_BulkTDB_Report_SubContractRowChangeEventHandler VIEW_BulkTDB_Report_SubContractRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddVIEW_BulkTDB_Report_SubContractRow(VIEW_BulkTDB_Report_SubContractRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public VIEW_BulkTDB_Report_SubContractRow AddVIEW_BulkTDB_Report_SubContractRow(string InspDate, string FamilyDesc, string BPCNONBPC, string Status, string SubContract, string FlagRL, string FormulaType) {
                VIEW_BulkTDB_Report_SubContractRow rowVIEW_BulkTDB_Report_SubContractRow = ((VIEW_BulkTDB_Report_SubContractRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        InspDate,
                        FamilyDesc,
                        BPCNONBPC,
                        Status,
                        SubContract,
                        FlagRL,
                        FormulaType};
                rowVIEW_BulkTDB_Report_SubContractRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowVIEW_BulkTDB_Report_SubContractRow);
                return rowVIEW_BulkTDB_Report_SubContractRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                VIEW_BulkTDB_Report_SubContractDataTable cln = ((VIEW_BulkTDB_Report_SubContractDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new VIEW_BulkTDB_Report_SubContractDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnInspDate = base.Columns["InspDate"];
                this.columnFamilyDesc = base.Columns["FamilyDesc"];
                this.columnBPCNONBPC = base.Columns["BPCNONBPC"];
                this.columnStatus = base.Columns["Status"];
                this.columnSubContract = base.Columns["SubContract"];
                this.columnFlagRL = base.Columns["FlagRL"];
                this.columnFormulaType = base.Columns["FormulaType"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnInspDate = new global::System.Data.DataColumn("InspDate", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnInspDate);
                this.columnFamilyDesc = new global::System.Data.DataColumn("FamilyDesc", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFamilyDesc);
                this.columnBPCNONBPC = new global::System.Data.DataColumn("BPCNONBPC", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBPCNONBPC);
                this.columnStatus = new global::System.Data.DataColumn("Status", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnStatus);
                this.columnSubContract = new global::System.Data.DataColumn("SubContract", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSubContract);
                this.columnFlagRL = new global::System.Data.DataColumn("FlagRL", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFlagRL);
                this.columnFormulaType = new global::System.Data.DataColumn("FormulaType", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFormulaType);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public VIEW_BulkTDB_Report_SubContractRow NewVIEW_BulkTDB_Report_SubContractRow() {
                return ((VIEW_BulkTDB_Report_SubContractRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new VIEW_BulkTDB_Report_SubContractRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(VIEW_BulkTDB_Report_SubContractRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.VIEW_BulkTDB_Report_SubContractRowChanged != null)) {
                    this.VIEW_BulkTDB_Report_SubContractRowChanged(this, new VIEW_BulkTDB_Report_SubContractRowChangeEvent(((VIEW_BulkTDB_Report_SubContractRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.VIEW_BulkTDB_Report_SubContractRowChanging != null)) {
                    this.VIEW_BulkTDB_Report_SubContractRowChanging(this, new VIEW_BulkTDB_Report_SubContractRowChangeEvent(((VIEW_BulkTDB_Report_SubContractRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.VIEW_BulkTDB_Report_SubContractRowDeleted != null)) {
                    this.VIEW_BulkTDB_Report_SubContractRowDeleted(this, new VIEW_BulkTDB_Report_SubContractRowChangeEvent(((VIEW_BulkTDB_Report_SubContractRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.VIEW_BulkTDB_Report_SubContractRowDeleting != null)) {
                    this.VIEW_BulkTDB_Report_SubContractRowDeleting(this, new VIEW_BulkTDB_Report_SubContractRowChangeEvent(((VIEW_BulkTDB_Report_SubContractRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveVIEW_BulkTDB_Report_SubContractRow(VIEW_BulkTDB_Report_SubContractRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsBulkTDB_Report_SubContract ds = new dsBulkTDB_Report_SubContract();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "VIEW_BulkTDB_Report_SubContractDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class VIEW_BulkTDB_Report_SubContractRow : global::System.Data.DataRow {
            
            private VIEW_BulkTDB_Report_SubContractDataTable tableVIEW_BulkTDB_Report_SubContract;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal VIEW_BulkTDB_Report_SubContractRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableVIEW_BulkTDB_Report_SubContract = ((VIEW_BulkTDB_Report_SubContractDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string InspDate {
                get {
                    try {
                        return ((string)(this[this.tableVIEW_BulkTDB_Report_SubContract.InspDateColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'InspDate\' in table \'VIEW_BulkTDB_Report_SubContract\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableVIEW_BulkTDB_Report_SubContract.InspDateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string FamilyDesc {
                get {
                    try {
                        return ((string)(this[this.tableVIEW_BulkTDB_Report_SubContract.FamilyDescColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FamilyDesc\' in table \'VIEW_BulkTDB_Report_SubContract\' is D" +
                                "BNull.", e);
                    }
                }
                set {
                    this[this.tableVIEW_BulkTDB_Report_SubContract.FamilyDescColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string BPCNONBPC {
                get {
                    try {
                        return ((string)(this[this.tableVIEW_BulkTDB_Report_SubContract.BPCNONBPCColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BPCNONBPC\' in table \'VIEW_BulkTDB_Report_SubContract\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableVIEW_BulkTDB_Report_SubContract.BPCNONBPCColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Status {
                get {
                    try {
                        return ((string)(this[this.tableVIEW_BulkTDB_Report_SubContract.StatusColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Status\' in table \'VIEW_BulkTDB_Report_SubContract\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableVIEW_BulkTDB_Report_SubContract.StatusColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string SubContract {
                get {
                    try {
                        return ((string)(this[this.tableVIEW_BulkTDB_Report_SubContract.SubContractColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SubContract\' in table \'VIEW_BulkTDB_Report_SubContract\' is " +
                                "DBNull.", e);
                    }
                }
                set {
                    this[this.tableVIEW_BulkTDB_Report_SubContract.SubContractColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string FlagRL {
                get {
                    try {
                        return ((string)(this[this.tableVIEW_BulkTDB_Report_SubContract.FlagRLColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FlagRL\' in table \'VIEW_BulkTDB_Report_SubContract\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableVIEW_BulkTDB_Report_SubContract.FlagRLColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string FormulaType {
                get {
                    try {
                        return ((string)(this[this.tableVIEW_BulkTDB_Report_SubContract.FormulaTypeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FormulaType\' in table \'VIEW_BulkTDB_Report_SubContract\' is " +
                                "DBNull.", e);
                    }
                }
                set {
                    this[this.tableVIEW_BulkTDB_Report_SubContract.FormulaTypeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsInspDateNull() {
                return this.IsNull(this.tableVIEW_BulkTDB_Report_SubContract.InspDateColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetInspDateNull() {
                this[this.tableVIEW_BulkTDB_Report_SubContract.InspDateColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsFamilyDescNull() {
                return this.IsNull(this.tableVIEW_BulkTDB_Report_SubContract.FamilyDescColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetFamilyDescNull() {
                this[this.tableVIEW_BulkTDB_Report_SubContract.FamilyDescColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsBPCNONBPCNull() {
                return this.IsNull(this.tableVIEW_BulkTDB_Report_SubContract.BPCNONBPCColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetBPCNONBPCNull() {
                this[this.tableVIEW_BulkTDB_Report_SubContract.BPCNONBPCColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsStatusNull() {
                return this.IsNull(this.tableVIEW_BulkTDB_Report_SubContract.StatusColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetStatusNull() {
                this[this.tableVIEW_BulkTDB_Report_SubContract.StatusColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSubContractNull() {
                return this.IsNull(this.tableVIEW_BulkTDB_Report_SubContract.SubContractColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSubContractNull() {
                this[this.tableVIEW_BulkTDB_Report_SubContract.SubContractColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsFlagRLNull() {
                return this.IsNull(this.tableVIEW_BulkTDB_Report_SubContract.FlagRLColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetFlagRLNull() {
                this[this.tableVIEW_BulkTDB_Report_SubContract.FlagRLColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsFormulaTypeNull() {
                return this.IsNull(this.tableVIEW_BulkTDB_Report_SubContract.FormulaTypeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetFormulaTypeNull() {
                this[this.tableVIEW_BulkTDB_Report_SubContract.FormulaTypeColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class VIEW_BulkTDB_Report_SubContractRowChangeEvent : global::System.EventArgs {
            
            private VIEW_BulkTDB_Report_SubContractRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public VIEW_BulkTDB_Report_SubContractRowChangeEvent(VIEW_BulkTDB_Report_SubContractRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public VIEW_BulkTDB_Report_SubContractRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591